server:
  host: "127.0.0.1"
  port: 8000
  reload: true

redis:
  host: "localhost"
  port: 6379
  password: null

mysql:
  host: "localhost"
  port: 3306
  database: "btl_mobile"
  user: "btl"
  password: "secret"

jwt:
  secret: "x4VdC7q1c9k9p2M0JrTgBzFqWmYhL3NsU8QaR5XeZiK1PoSdHgTyWuQeRtY1UiOp"
  algorithm: "HS256"
  expire_minutes: 60
